export const SCREEN_DECK_LIST = "SCREEN_DECK_LIST";
export const SCREEN_DECK_DETAILS = "SCREEN_DECK_DETAILS";
export const SCREEN_HOME = "SCREEN_HOME";
export const SCREEN_ADD_DECK = "SCREEN_ADD_DECK";